### ISSUE TITLE
Adding corpuses in the Django app

### ISSUE THREAD

**Issue by BLCKPSTV** [gunthercox/chatterbot-corpus#11]
How can I add existing corpuses and new corpus json files to the Django example app?

**Comment by vkosuri** [comment]
I think this could help you http://chatterbot.readthedocs.io/en/stable/training.html#specifying-corpus-scope

**Comment by BLCKPSTV** [comment]
Wel I'm looking at the files(it's in this repository)... So in that sense I know how they work. I just don't know how to implement custom made file that is in my own directory to be read by the chatterbot (VIA Django)?

**Comment by vkosuri** [comment]
Can you try like this? I think training through external files not implemented for Django

CHATTERBOT = {
    # ...
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': [
         '"./data/my_corpus/"'
    ]
}

See some more documentation http://chatterbot.readthedocs.io/en/stable/django/training.html#training-settings

**Comment by BLCKPSTV** [comment]
When adding `"./data/english/"` in my settings.py and putting a data folder with a folder inside where the english corpus reside I get following errors when `python manage.py train`.

```
python manage.py train
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/chatterbot/ext/django_chatterbot/management/commands/train.py", line 19, in handle
    chatterbot.train(chatterbot.training_data)
  File "/usr/local/lib/python2.7/site-packages/chatterbot/trainers.py", line 114, in train
    corpus_data = self.corpus.load_corpus(corpus)
  File "/usr/local/lib/python2.7/site-packages/chatterbot_corpus/corpus.py", line 71, in load_corpus
    corpus = self.read_corpus(file_path)
  File "/usr/local/lib/python2.7/site-packages/chatterbot_corpus/corpus.py", line 39, in read_corpus
    with io.open(file_name, encoding='utf-8') as data_file:
IOError: [Errno 2] No such file or directory: './data/english/'
```

**Comment by vkosuri** [comment]
The problem is there are no files exist in current directory. Did you created any corpus files in your current directory?

**Comment by BLCKPSTV** [comment]
In my `"example_folder"` I have a `"data"` folder within that folder I have a folder called` "english"` and in that folder I have the English corpus.json files from ai to trivia.json. 

I've pushed this local folder via git `add . , git commit -m "added local corpus", git push heroku master`

the line of code in the settings.py == 

```
CHATTERBOT = {
    'name': 'Django ChatterBot Example',
    'logic_adapters' : [
        "chatterbot.logic.MathematicalEvaluation",
        "chatterbot.logic.BestMatch"
    ],
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': [
        'chatterbot.corpus',
        'data/english/greetings.corpus2'
    ]
}
```
Any idea what's going wrong? I would love to add my own corpus to my bot. 
additional question: Does the data folder have to be in the static folder?

**Comment by vkosuri** [comment]
Any about this issue

**Comment by gunthercox** [comment]
I've opened a pull request that adds tests to verify that paths to custom corpora can be specified. I also can't recreate the other issues that were reported in the comments. Is this issue is still being encountered, make sure that you have the latest version of ChatterBot and the chatterbot corpus installed. This can be done by running `pip install chatterbot --upgrade`. If you still encounter the issues after that be sure to check that you have specified the correct path to the corpus file.
