### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by jayaprakash2705** [gunthercox/chatterbot-corpus#118]
C:\Users\user>cd desktop

C:\Users\user\Desktop>python ourchatbot.py
ourchatbot.py:8: SyntaxWarning: invalid escape sequence \D
  for files in os.listdir('C:/Users/user\Desktop\chatterbot-corpus-master\chatterbot_corpus\data\english/'):
ourchatbot.py:9: SyntaxWarning: invalid escape sequence \D
  data = open ('C:/Users/user\Desktop\chatterbot-corpus-master\chatterbot_corpus\data\english/'+ files,'r').readlines()
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Traceback (most recent call last):
  File "ourchatbot.py", line 6, in <module>
    bot.set_trainer(ListTrainer)
AttributeError: 'ChatBot' object has no attribute 'set_trainer'

**Comment by gunthercox** [comment]
This sounds very similar to this issue https://github.com/gunthercox/ChatterBot/issues/1555#issuecomment-453700386

**Comment by mady143** [comment]
I had changed the code as per your request but i am getting another error which is similar to past i have got please check bellow code



from flask import Flask, render_template, request
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

app = Flask(__name__)

english_bot = ChatBot("Chatterbot", storage_adapter="chatterbot.storage.SQLStorageAdapter")

english_bot.ListTrainer(english_bot)
english_bot.train("./data")


@app.route("/")
def home():
    return render_template("index.html")

@app.route("/get")
def get_bot_response():
    userText = request.args.get('msg')
    return str(english_bot.get_response(userText))


if __name__ == "__main__":
    app.run()

**ERROR**

Traceback (most recent call last):
  File "app.py", line 9, in <module>
    english_bot.ListTrainer(english_bot)
AttributeError: 'ChatBot' object has no attribute 'ListTrainer'

**Comment by vkosuri** [comment]
You need to change your example like this
``` Python
from chatterbot.trainers import ListTrainer

conversation = [
    "Hello",
    "Hi there!",
    "How are you doing?",
    "I'm doing great.",
    "That is good to hear",
    "Thank you.",
    "You're welcome."
]

trainer = ListTrainer(chatbot)

trainer.train(conversation)
```
