### ISSUE TITLE
Chatterbot reading .yml files as text files

### ISSUE THREAD

**Issue by bufferbox** [gunthercox/chatterbot-corpus#128]
When I try to train the bot in a .yml format file that is available in 'chatterbot_corpus/data/english/botprofile.yml', the bot responds with sentences along with hyphens. How can I train the bot in such a way that it replies without hyphens?

It seems as if it did not recognize the file as a .yml and is just reading it as a text file.

![image](https://user-images.githubusercontent.com/38717946/56090504-8b3d9c00-5eab-11e9-9204-5e0fc0327708.png)

**Comment by gunthercox** [comment]
ChatterBot's training process respects the preprocessors that are configured for the chatbot being trained. Because of this you could create a preprocessor that removes hyphens.

https://chatterbot.readthedocs.io/en/stable/preprocessors.html

```
def remove_hyphens(statement):
    """
    Remove hypnens.
    """
    statement.text = statement.text.replace('-', '')

    return statement


chatbot = ChatBot(
    'Example,
    preprocessors=[
        remove_hyphens
    ]
)
```

**Comment by bufferbox** [comment]
This is the error I'm getting after trying that:
AttributeError: module 'chatterbot.preprocessors' has no attribute 'remove_hyphens'

Here is my code:
from chatterbot.trainers import ListTrainer
from chatterbot import ChatBot
from chatterbot.conversation import Statement
import os

bot = ChatBot('Test',
      storage_adapter='chatterbot.storage.SQLStorageAdapter',
      database_uri='sqlite:///database.sqlite3',
      logic_adapters=[
                      'chatterbot.logic.MathematicalEvaluation',
                      {
                        'import_path': 'chatterbot.logic.BestMatch',
                        'default_response': 'I am sorry, but I do not understand.',
                        'maximum_similarity_threshold': 0.90
                      }
                    ],
      preprocessors=[
                     remove_hyphens
                     ],
      trainer='chatterbot.trainers.ListTrainer')

trainer = ListTrainer(bot)

for _file in os.listdir('files'):
    chats = open('files/' + _file, 'r').readlines()
    trainer.train(chats)

def remove_hyphens(statement):
    """
    Remove hypnens.
    """
    statement.text = statement.text.replace('-', '')
    return statement

while True:
    try:
        message = input('You:')
        if message.strip() == 'Bye':
            print('ChatBot: Bye')
            break
        else:
            reply = bot.get_response(message)
            if reply.confidence == 0:
                print("I don't understand")
            else:
                print('ChatBot:', reply)

    # Press ctrl-c or ctrl-d on the keyboard to exit
    except (KeyboardInterrupt, EOFError, SystemExit):
        break

**Comment by gunthercox** [comment]
You are seeing that error because you need to define the `remove_hyphens` function before you reference it in the `ChatBot` instance. (Just move the `remove_hyphens` before the `bot =` line.)

**Comment by bufferbox** [comment]
Yes, you're right.
However, I am getting this error now: [AttributeError: 'function' object has no attribute 'split']

Traceback (most recent call last):
  File "C:\Users\zarai\AppData\Local\Programs\Python\Python37-32\practise\newtrial\improved main\improvedMain.py", line 30, in <module>
    trainer='chatterbot.trainers.ListTrainer')
  File "C:\Users\zarai\AppData\Local\Programs\Python\Python37-32\lib\site-packages\chatterbot\chatterbot.py", line 50, in __init__
    self.preprocessors.append(utils.import_module(preprocessor))
  File "C:\Users\zarai\AppData\Local\Programs\Python\Python37-32\lib\site-packages\chatterbot\utils.py", line 14, in import_module
    module_parts = dotted_path.split('.')
AttributeError: 'function' object has no attribute 'split'

**Comment by gunthercox** [comment]
You might need to move the remove_hyphens function into it's own python file. Once you make that change, you should be able to modify the corresponding value in the preprocessors list to be a string representing a relative import.

**Comment by bufferbox** [comment]
I tried that and now I am getting a different kind of error. Hope you can help me.

`
from chatterbot.trainers import ListTrainer
from chatterbot import ChatBot
import os

bot = ChatBot('Test',
      storage_adapter='chatterbot.storage.SQLStorageAdapter',
      database_uri='sqlite:///database.sqlite3',
      logic_adapters=[
                      {
                        'import_path': 'chatterbot.logic.BestMatch',
                        'default_response': 'I am sorry, but I do not understand.',
                        'maximum_similarity_threshold': 0.95
                      }
                    ],
      preprocessors= [{'import_path':'chatterbot.preprocessors.remove_hyphens'}],
      trainer='chatterbot.trainers.ListTrainer')

trainer = ListTrainer(bot)

for _file in os.listdir('files'):
    chats = open('files/' + _file, 'r').readlines()
    trainer.train(chats)

while True:
    try:

        message = input('You:')

        if message.strip() == 'Bye':
            print('ChatBot: Bye')
            break
        else:
            reply = bot.get_response(message)
            if reply.confidence == 0:
                print("Chatbot: I don't understand")
            else:
                print('ChatBot:', reply)

    # Press ctrl-c or ctrl-d on the keyboard to exit
    except (KeyboardInterrupt, EOFError, SystemExit):
        break
`

Error:
`
Traceback (most recent call last):
  File "C:\Users\wasai\AppData\Local\Programs\Python\Python37-32\practise\newtrial\improved main\improvedMain.py", line 19, in <module>
    trainer='chatterbot.trainers.ListTrainer')
  File "C:\Users\wasai\AppData\Local\Programs\Python\Python37-32\lib\site-packages\chatterbot\chatterbot.py", line 50, in __init__
    self.preprocessors.append(utils.import_module(preprocessor))
  File "C:\Users\wasai\AppData\Local\Programs\Python\Python37-32\lib\site-packages\chatterbot\utils.py", line 14, in import_module
    module_parts = dotted_path.split('.')
AttributeError: 'dict' object has no attribute 'split'
>>> 
`

**Comment by gunthercox** [comment]
Here is an alternative method you can try:

```
def remove_hyphens(statement):
    # ...

bot = ChatBot('Test',
    # ...
)

bot.preprocessors.append(
    remove_hyphens
)

trainer = ListTrainer(bot)
# ...
```

By doing this, you can retroactively add your custom preprocessor to the chat bot.

**Comment by bufferbox** [comment]
Thank you! It works now :)
