### ISSUE TITLE
Attribute error while training on yml corpus

### ISSUE THREAD

**Issue by AhmadManzoor** [gunthercox/chatterbot-corpus#169]
/home/abubakar/.local/lib/python3.6/site-packages/chatterbot/corpus.py:38: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(data_file)
Training movies_google_assistant.yml: [#                   ] 7%Traceback (most recent call last):
  File "chatbot.py", line 9, in <module>
    trainer.train('/home/abubakar/Desktop/movies_google_assistant.yml')
  File "/home/abubakar/.local/lib/python3.6/site-packages/chatterbot/trainers.py", line 157, in train
    statement_search_text = self.chatbot.storage.tagger.get_bigram_pair_string(text)
  File "/home/abubakar/.local/lib/python3.6/site-packages/chatterbot/tagging.py", line 159, in get_bigram_pair_string
    for sentence in self.tokenize_sentence(text.strip()):
AttributeError: 'list' object has no attribute 'strip'

**Comment by NitValen** [comment]
I have the same error. Did you solve the problem ?

**Comment by Ahmad-noborders** [comment]
please recheck your training file and validate if there is no syntax problem. try with lesser data and see if problem persists.

**Comment by in11f4** [comment]
Reviving an old thread. 
@NitValen : Use the right format of the yml file. If you have any doubts, example: 


categories:
- conversations
conversations:
- -Good Evening
  -Hey, I am your qTest Chatbot
- -Hello
  -Hey how are you?
- -I need help on TestPlan
  -Please click on this link
- -Do you have any video training material?
  -Yes
