### ISSUE TITLE
Format for adding new corpus?

### ISSUE THREAD

**Issue by peterel** [gunthercox/chatterbot-corpus#19]
Hey, 

I see that one is able to add new corpus:es. But how would one go about doing that for adding e.g. the Cornell Movie DB (https://www.cs.cornell.edu/~cristian/Cornell_Movie-Dialogs_Corpus.html)? Would one need to parse the entire DB and create a huge json in the similar format as current corpus:es as per below?

[
            "Good morning, how are you?",
            "I am doing well, how about you?",
            "I'm also good.",
            "That's good to hear.",
            "Yes it is."
],
...

Thanks.

**Comment by vkosuri** [comment]
Yes, Use python template mechanism ti translate entire data

**Comment by peterel** [comment]
Hmm, ok, what is the "python template mechanism"?

**Comment by vkosuri** [comment]
I mean translating such huge data into JSON will take more time, instead you could write a small wrapper that will translate cornell movie dialogs into chatterbot corpus.

**Comment by peterel** [comment]
Ok, I see. Ill check how to do that. Any tips one where to start is appreciated.

In any case, then I know. To use the cornell movie dialog corpus, Id need to first translate it to a json structure as per below per dialog.

[
"Good morning, how are you?",
"I am doing well, how about you?",
"I'm also good.",
"That's good to hear.",
"Yes it is."
],
...

**Comment by vkosuri** [comment]
Before proceeding further did you checked that are there any license conflicts between https://www.cs.cornell.edu/%7Ecristian/Cornell_Movie-Dialogs_Corpus.html and [corpus-chatterbot](https://github.com/gunthercox/chatterbot-corpus/blob/master/license.md).

I mean to say Cornell_Movie-Dialogs comes under which license?

**Comment by peterel** [comment]
I believe its free to use/alter/change...but Ill check before moving forward.

Thanks. Ill close this now and re-open should I move forward and get stuck somewhere where I cant get out :)

**Comment by vkosuri** [comment]
@peterel I am going reopen this issue, Insted getting approval, you could write your own train class by extending chatterbot train class. see example how nltk is doing http://www.nltk.org/_modules/nltk/corpus/reader/conll.html

**Comment by peterel** [comment]
@vkosuri There is no big point in doing that. There is a limit, see other tickets, for using larger corpus on chatterbot.

**Comment by vkosuri** [comment]
Thanks

**Comment by peterel** [comment]
@vkosuri Thanks, will do.
