### ISSUE TITLE
pymongo.errors.OperationFailure for Ubuntu corpus

### ISSUE THREAD

**Issue by peterel** [gunthercox/chatterbot-corpus#21]
Hi,

Ive trained the chatterbot (for a while, maybe 15 hours) over the Ubuntu corpus. The training is not finished but it got aborted (my computer went to sleep) so I thought Id try it out to see what effect it had. However, I just get below error. Any idea what to do about this?

pymongo.errors.OperationFailure: distinct too big, 16mb cap

Thanks.

**Comment by gunthercox** [comment]
Hi @peterel, I believe this issue has already been record here: https://github.com/gunthercox/ChatterBot/issues/686 

I'm working on a solution for retrieving data from multi-gigabyte data sets. An update will be provided through the main ChatterBot distribution once this functionality is corrected.

**Comment by peterel** [comment]
@gunthercox Ok, sounds good! Any ETA on that?

**Comment by gunthercox** [comment]
Not currently, but it is high priority for me now that I'm seeing so many cases where developers want to use ChatterBot for very large data sets.

**Comment by peterel** [comment]
@gunthercox Ok. I think it becomes more and more an issue since the Ubuntu corpus is "built in" the chatterbot docs. Makes sense to use it since its so accessible. Using only the language specific corpus (english etc) doesnt yield very good responses. I think thats why people looking to use Chatterbot get stuck on this. If there is a smaller corpus than ubuntu but bigger than the language specific ones, that would be a great first step. Do you know of any?

**Comment by gunthercox** [comment]
I'm sure there is a moderate sized dialog corpus out there, however there isn't any that presently come to mind.

**Comment by peterel** [comment]
@gunthercox Ok, thanks. If you hear of any, Im all ears :)
