### ISSUE TITLE
Where can I find more corpora for ChatterBot?

### ISSUE THREAD

**Issue by peterel** [gunthercox/chatterbot-corpus#22]
Hi,

Using the "built in english" corpus gives some decent answers but its really far to few to build a nice conversation bot. 

Using the "built in Ubuntu corpus" gives an error (16 mbit pymongo error, already reported and hopefully soon worked on).

So, what choices do I have? Is there some "conversational corpus", which is not as big as the Unbuntu corpus to cause the pymongo errors, but still bigger than the built in english corpus? Im "only" looking to train the bot to hold a decent conversation, no need to debate meaning of life but should be reliable in "normal conversation".

Thanks.

**Comment by gunthercox** [comment]
Data contributions to https://github.com/gunthercox/chatterbot-corpus are welcome and are a great way to increase the size of the corpus.

**Comment by rushilsrivastava** [comment]
You may want to look into formatting your own questions, and then training your bot with them.
