### ISSUE TITLE
Identify "Corpus" by IETF language tag rather than just language

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/chatterbot-corpus#24]
> My suggestion is to Identify the "Corpus" by [IETF language tag](https://en.wikipedia.org/wiki/IETF_language_tag) rather than just language. What are the benefits? it would allow for different dialects to be made independent as i might want to just "teach" just one of them. 
> ### Why i'm bringging this idea up?
> For example the corpus for the _Portuguese_ language taking a look at it seems to have mostly _Portuguese Brazilian_ (**pt-BR**) strings and some, here and there, in the Portuguese (**pt** or **pt-PT**). Using said corpus makes the bot a bit of biliangual freak, i'f im allowed to call it that :P
> 
> Same goes for the english corpus which, i'd say (not totally sure, but from some expressions), is _English_ (**en** or **en-GB**) with  _United States English_ (**en-US**) in it.
> 
> Chinese is another language with _ALOT_ of dialects.. (but this one is an unkown to me as i have zero knowledge in the language) 
> The story goes on..
> 
> ~ @duramato

_This ticket was originally opened in the ChatterBot repository when the corpus files were a part of the main package.  I've moved it here to keep track of it as the projects move forward._

**Previous ticket:** https://github.com/gunthercox/ChatterBot/issues/504

**Comment by vkosuri** [comment]
@gunthercox Master, Are we going handle to through NLTK like said here http://blog.alejandronolla.com/2013/05/15/detecting-text-language-with-python-and-nltk/

If not any alternative methods to do this?

**Comment by gunthercox** [comment]
@vkosuri Nope, data within a corpus should be explicitly labeled and categorized. The data it contains is what other systems train with and they assume that it is correct. We shouldn't need to automatically detect too much, we just need to re-label the current directory structure and provide aliases for backward compatibility.

**Comment by gunthercox** [comment]
I'm going to leave these as the english language names for now. I've opened #121 to at least make sure that the names are all consistent.

**Comment by gunthercox** [comment]
I'll defer to #40 for the possible design of making the structure of the data independent of language type. One way to achieve this could be to tag language on a per-line basis.
