### ISSUE TITLE
Corpus to include entities?

### ISSUE THREAD

**Issue by andreaskviby** [gunthercox/chatterbot-corpus#29]
Look at this question and hopefully let me know if this can be done.

I use the chatterbot library for creating a bot about food. I need it to learn about entities so that a question about meatballs can have the same response action like the question about pasta. Is it possible to make chatterbot learn entities or could we add a corpus like dictionary with all entities our bot should know about?

**Comment by gunthercox** [comment]
So, for example, are you imagining something like this?

**foods.json**
```json
{
   "meatballs": {
        "toppings": [
            "cheese",
            "oregano"
        ]
   },
   "pasta": {
        "toppings": [
            "cheese",
            "tomato sauce"
        ]
   },
   "salad": {
        "toppings": [
            "dressing"
        ],
        "dressing_types": [
            "italian",
            "balsamic",
           "ranch"
        ]
   }
}
```

There is a good chance this can't be done because the chat bot doesn't have a way to interpret unstructured data such as this. I just figured I'd verify with an example before diving too deep into an explanation.

**Comment by andreaskviby** [comment]
Yes that would be awesome

Med vänliga hälsningar

Andreas Kviby
PILGRIMSBO FÖRETAGSUTVECKLING AB
andreas@pilgrimsbo.se
Telefon 0155-910 20
Skype andreaskviby

Support ges på
support@pilgrimsbo.se

Alla vardagar mellan 10-16 förutom fredagar då support bara ges mellan 10-13.
