### ISSUE TITLE
Switch from ruamel.yaml to PyYAML

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/chatterbot-corpus#35]
This is in response to https://github.com/gunthercox/ChatterBot/issues/913#issuecomment-321441775

[PyYAML](https://pypi.python.org/pypi/PyYAML) seems like a better choice considering that a number of large projects depend on it. For example, the `docker-compose` project https://github.com/docker/compose/blob/f9aaa72c54957ee834141bdf7f7ec9b656f26697/requirements.txt#L17

**Comment by Issen007** [comment]
With the sort reading I have done it seams to be a better choice.
