### ISSUE TITLE
Untraining Chatterbot

### ISSUE THREAD

**Issue by ayushecps** [gunthercox/chatterbot-corpus#41]
How to untrain Chatterbot once it is wrongly trained ?

**Comment by vkosuri** [comment]
Currently there is no feature avaliable. However you could delete ``db.sqlite`` file from your directory

**Comment by ayushecps** [comment]
i have deleted the db.sqlite file but now it is throwing error.


![error](https://user-images.githubusercontent.com/31202855/29994990-8e7c6200-8ffb-11e7-8e85-ef9c55fcb6f0.png)

**Comment by vkosuri** [comment]
Every deletion you have to reteain the bot

``
python manage.py train
``

**Comment by MayankGupta3090** [comment]
could you please explain the steps how should i retain the bot .. i mean how can i deletethe sqlite file and train the bot ..please help. i m beginner

**Comment by MayankGupta3090** [comment]
I did following:
1. deleted the db.sqlite file
2. then train the bot
during the training it errorout with the error as my friend ayush commented before. please help us in fixing the issue

**Comment by vkosuri** [comment]
I these steps will solve your problem

```
python manage.py makemigrations
python manage.py train
python manage.py runserver
```

**Comment by ayushecps** [comment]
All command I am running in the directory where the manage file is stored right ?

When I run
python manage.py makemigrations
It says no changes detected

While after running above command I run python manage.py train it again gave me same error

**Comment by vkosuri** [comment]
can you try like this

```bash
python manage.py syncdb
python manage.py migrate
python manage.py makemigrations 
```

If not try these instructions  https://github.com/gunthercox/ChatterBot/pull/923#issuecomment-322621800

**Comment by ayushecps** [comment]
Hi ,

I have already done with migrate statement.. Thanks for all your help !!!
Now I am facing issue in getting exact response from chatbot as what I have
written in .yml files.
I am a beginner, please help.

**Comment by Issen007** [comment]
@ayushecps If this is solve, can you please close this ticket.
If you get the wrong responds to a statement. Please open a new ticket so it will be easier for us to keep track what's is a bug or not.

**Comment by Issen007** [comment]
@vkosuri you shouldn't delete the entire sqlite file to untrain the chatterbot.
Especially not when you are using it with Django. In that case you can only mark the wrong data and delete that row  (Statement/Responds) or you can modify that statement / responds to the correct answer.

**Comment by vkosuri** [comment]
@Issen007 said is correct.

**Comment by Issen007** [comment]
Haven't got any answer on this. Will close this ticket.
