### ISSUE TITLE
Dynamic repsonds

### ISSUE THREAD

**Issue by Issen007** [gunthercox/chatterbot-corpus#43]
Is it possible to add a dynamic responds?
What I'm looking for is. If I ask the chatbot what time or date it is, I want to get the responds on the current time and date that the localhost has.

Thanks

**Comment by vkosuri** [comment]
If are looking speicfic time related queires, chatterbot has already ``TimeLogicAdapter`` https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/logic/time_adapter.py

And some documentation here http://chatterbot.readthedocs.io/en/stable/logic/index.html#time-logic-adapter
