### ISSUE TITLE
Inaccurate conversations in Hindi and Marathi due to literal translation.

### ISSUE THREAD

**Issue by Sudha247** [gunthercox/chatterbot-corpus#59]
This is one of the greetings in Hindi data
- - क्या हो रहा है?
  - आकाश के ऊपर है, लेकिन मैं। आप के बारे में क्या ठीक धन्यवाद कर रहा हूँ?
This seems to be a literal translation of its English counterpart.
- - What's up?
  - The sky's up but I'm fine thanks. What about you?
But the Hindi one doesn't make much sense because "क्या हो रहा है?" --> "What's going on?" and "आकाश के ऊपर है, लेकिन मैं। आप के बारे में क्या ठीक धन्यवाद कर रहा हूँ?" --> " The sky's up but I'm fine thanks. What am I doing"
Same is the case with Marathi.
I presume the Hindi and Marathi data were generated by translating English ones on Google Translate. There are some more minor inaccuracies in Hindi data. 
I could work on fixing this.
I could also add data for Tamil.

**Comment by vkosuri** [comment]
@Sudha247 Thanks
