### ISSUE TITLE
support for regex and dynamic responses

### ISSUE THREAD

**Issue by mikkokotila** [gunthercox/chatterbot-corpus#63]
What do you think it would take to have the possibility of using regex, for example, in the case of zipcode being the zipcode (i.e. if the user input is zipcode, the response is always the same). 

The other part of this is "dynamic" responses where depending on the user input, an otherwise standard response is transformed in some way (e.g. confirming the zipcode to be correct).

What do you think?

**Comment by vkosuri** [comment]
This something you could achieve through chatterbot preprocessors http://chatterbot.readthedocs.io/en/stable/preprocessors.html
