### ISSUE TITLE
Make corpus data available to other programming languages

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/chatterbot-corpus#7]
Because the data files in the chatterbot corpus are not Python specific, it should be possible to add packaging for other programming languages as well. I would be interested in experimenting to see how successfully this could be accomplished with a language such as None JS.

**Comment by vkosuri** [comment]
@gunthercox Apologies Master, i can't make this due to my [PSI](http://www.scaledagileframework.com/welcome-to-safe-40/). I will try to add some of my inputs here by COB.

**Comment by vkosuri** [comment]
@gunthercox Master, i am thinking like this, do you have any comments?

copy_corpus.py
```Python
import os
import shutil
import subprocess

def corpus_copy(src, dest):
    """ copy entire directory into specified location
    Params:
        src: Source Directory path
        dest: Destination directory path
    Raises:
        OSError: The system cannot find the path specified
    """
    try:
        shutil.copytree(src, dest)
    except OSError as e:
        # If the error was caused because the source wasn't a directory
        if e.errno == errno.ENOTDIR:
            shutil.copy(src, dest)
        else:
            # print('Directory not copied. Error: %s' % e)
            logger.debug('ERROR: Directory can not copied!!! Reason: %s' % e)
            return False
    
    return True

corpus_data = os.path.join(os.path.sep, chatterbot_path[0], 'corpus', 'data')

# git clone the chatterbot-corpus
process = subprocess.Popen(["git", "clone", "https://github.com/gunthercox/chatterbot-corpus"], stdout=subprocess.PIPE)
output = process.communicate()[0]

# Move chatterbot-corpus data to chatterbot
corpus_copy('corpus/data/', corpus_data)
```

Usage:

``` Bash
(virtualenv)vkosuri$ python copy_corpus.py
```

**Comment by AmusingThrone** [comment]
There are questions in the Corpus that ask about the language the bot is built in. To accomplish this, it would probably be smart to remove those questions.

**Comment by vkosuri** [comment]
I am trying to use [NLTK Data](http://www.nltk.org/api/nltk.corpus.html) It is quite good and very easy to use, I think could be an option to implement in chatterbot https://github.com/nltk/nltk/wiki/Adding-a-Corpus

**Comment by gunthercox** [comment]
I'm going to close this ticket off for now. Contributions and pull requests are welcome but this isn't going to be something I am focusing on right now.

**Comment by vkosuri** [comment]
@gunthercox One question, Our corpus is like statements and response, if we have implemented it looks something like this, or any other methods are you looking?

``` Python
from chatterbot.corpus.english import ai
print(", ".join(ai.words()))
```

**Comment by gunthercox** [comment]
@vkosuri, I do like that format and I've though about implementing something to allow it to be imported that way. I agree that it would be useful.
