### ISSUE TITLE
Missing hyphen in English training corpus file conversations.yml

### ISSUE THREAD

**Issue by IsabelMeraner** [gunthercox/chatterbot-corpus#73]
When training my bot on the provided English training corpora, there seems to be a problem when loading the file conversations.yml:

The question statement "- What languages do you like to use?" (line 90) is missing one hyphen, which causes the sentence to be split into single characters and to be stored as such in the database (in my case SQLite). This might lead to answers composed of single characters sometimes.

Can you check this problem and fix the file?
Thank you very much!

**Comment by gunthercox** [comment]
I've checked the file, I can't see to confirm this issue. (The version I'm viewing: https://github.com/gunthercox/chatterbot-corpus/blob/master/chatterbot_corpus/data/english/conversations.yml)

I suspect that I might need to release an updated version of the corpus to PyPi.
