### ISSUE TITLE
Several responses to a question

### ISSUE THREAD

**Issue by fhouget** [gunthercox/chatterbot-corpus#80]
Hello,
I have seen that in the "english", directory, in the "computers" file, several responses are written like that to the same questions : 
- - Question Q1
  - A
  - B
  - ...
whereas in most of others file, the question is repeated each time "ai.yml" for example)
- - Question Q1
  - A
- - Question Q1
  - B
Both solutions work or not ? If yes, is there any difference, and is the first one recommended or not ?

Not clear for me :)

**Comment by gunthercox** [comment]
Hi @fhouget, those represent different possible answers to the same question.

**Comment by fhouget** [comment]
OK, thanks for ur answer.
It's clear for me now.
But I have a doubt, I wonder if it was not understood diferently. I wonder if some people did not consider that this represents a conversation, and not the differents responses.
For exemple in "conversations.yml" in english directory, I can read : 
I did not look each file, it is just an exemple with one file, I think the same problem can appear in other files, in other languages

**Comment by gunthercox** [comment]
In that example the data represents an entire conversation.
