### ISSUE TITLE
translate all PT-BR

### ISSUE THREAD

**Issue by Humjava** [gunthercox/chatterbot-corpus#89]
i translated somethings to Pt-BR pls add this 
[money.txt](https://github.com/gunthercox/chatterbot-corpus/files/1999146/money.txt)
[movies.txt](https://github.com/gunthercox/chatterbot-corpus/files/1999147/movies.txt)
[politic.txt](https://github.com/gunthercox/chatterbot-corpus/files/1999148/politic.txt)
[proverbs.txt](https://github.com/gunthercox/chatterbot-corpus/files/1999149/proverbs.txt)
[psychology.txt](https://github.com/gunthercox/chatterbot-corpus/files/1999150/psychology.txt)
[science.txt](https://github.com/gunthercox/chatterbot-corpus/files/1999151/science.txt)
[trivia.txt](https://github.com/gunthercox/chatterbot-corpus/files/1999152/trivia.txt)
[computer.txt](https://github.com/gunthercox/chatterbot-corpus/files/1999153/computer.txt)
[emotions.txt](https://github.com/gunthercox/chatterbot-corpus/files/1999154/emotions.txt)
[food.txt](https://github.com/gunthercox/chatterbot-corpus/files/1999155/food.txt)
[history.txt](https://github.com/gunthercox/chatterbot-corpus/files/1999156/history.txt)
[humor.txt](https://github.com/gunthercox/chatterbot-corpus/files/1999157/humor.txt)
[literature.txt](https://github.com/gunthercox/chatterbot-corpus/files/1999158/literature.txt)

**Comment by vkosuri** [comment]
Thanks for your suggestions converting English into Brazilian Portuguese, Could you please create a pull request for these changes?

**Comment by Humjava** [comment]
idk create a pull request ;-
