### ISSUE TITLE
Untrain or create new chatterbot

### ISSUE THREAD

**Issue by nevank** [gunthercox/chatterbot-corpus#93]
So I'm very new to python and chatterbot. I have started training a bot and have made some minor grammatical errors such as 

Me: What is your name?
bot: Your name is DEX

Keeps saying this even after I set a new conversation trainer to try and correct it. So I'm trying to wipe the bot I currently have so I can start fresh. I can't seem to find where the data is stored. I'm using the python interpreter so I don't understand where the files are being stored. No files are attached to the python interpreter on my computer that has to do with chatterbot. Any help with be greatly appreciated thanks!

**Comment by cerofrais** [comment]
look for db.sqlite3 file, for me it is only one folder up. delete that and redo training with files you need.
