### ISSUE TITLE
Train from file

### ISSUE THREAD

**Issue by vltabacaru** [gunthercox/chatterbot-corpus#99]
Hi,
I wonder if it possible to train it from a specific file with conversations.
For example specify the file name in example_app/settings.py:
```
CHATTERBOT = {
    'name': 'ChatterBot Example',
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': [
#        'chatterbot.corpus.english.greetings'
        './data/custom.corpus/custom_conversations.txt'
    ],
    'django_app_name': 'django_chatterbot'
}
```
And in data/custom.corpus/custom_conversations.txt to have statements and responses like:
```
How are you?
I am doing great, thanks.
Do you enjoy the weather today?
Not really.
We should play some baseball.
I would love to play baseball.
```
So when I run the `python manage.py train` command, to get all these answers in my SQLite database.
How is this done? Thank you

**Comment by vltabacaru** [comment]
Got it. My example_app/settings.py looks like this:
```
CHATTERBOT = {
    'name': 'ChatterBot Example',
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': [
        './data/custom.corpus/conversations.yml'
    ],
    'django_app_name': 'django_chatterbot'
}
```
And data/custom.corpus/conversations.yml looks like [this](https://github.com/gunthercox/chatterbot-corpus/blob/master/chatterbot_corpus/data/english/conversations.yml).

**Comment by vkosuri** [comment]
:+1:
